				<li id="album-{%id}" class="album-row-dialog album-row">
					<div class="checkbox"><input type="checkbox" class="album-checkbox" id="album-checkbox-{%id}" value="{%id}" name="album[]" /></div>
					<div class="image"><img src="https://graph.facebook.com/{%id}/picture?type=small&access_token={%token}" /></div>
					<div class="info"><div class="album-name">{%name}</div>
					<div class="album-desc">{%desc}</div>
					</div>
				</li>
