
<li class="album_item " id="album_row_{%id}">
	<div class="album-image {%facebookClass}"><div style="background-image: url('{%preview}');background-repeat: no-repeat; width: 115px; height: 87px" class="img-drag"><div class="facebook_icon"></div></div></div>

	<div class="album-info-box {%facebookClass}">

		<div class="album-action-box delete-box" id="delete_{%id}"></div>
		<div class="album-action-box edit-box" id="edit_{%id}"></div>
		<div class="album-action-box refresh-album-box "  id="refresh_{%id}"></div>
		<div class="album-name">{%name}</div>
		<div class="album-desc"><b>{%location}</b>{%desc}</div>
	</div>
</li>
