<!doctype html>
<html>
<head>
	<title>Website Gallery - Admin Control Panel</title>
	<link href="css/login.css" rel='stylesheet' type='text/css' />
	<link href="css/button.css" rel='stylesheet' type='text/css' />
	<link type="text/css" rel="stylesheet" href="css/jquery-ui.css" />
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>
	<script type="text/javascript" src="js/button.js"></script>
	<script type="text/javascript" src="js/main.js"></script>


	<script type="text/javascript">

		function positionLoginForm () {
			// center the login box.
			var boxHeight = $('#global_container_login').height();
			var boxWidth = $('#global_container_login').width();

			var documentHeight = $(document).height();
			var documentWidth= $(document).width();


			var positionTop = (documentHeight/2) - (boxHeight/2) - (documentHeight*0.1);
			var positionLeft = (documentWidth/2) - (boxWidth/2);


			$('#global_container_login').css('top', positionTop + 'px');
			$('#global_container_login').css('left', positionLeft + 'px');

		}

		{%addJs}
		$(document).ready(function() {
			$('#message').hide();

			positionLoginForm();

			$("#install_button").bind('button_click', function() {
			$.post('action.php', {'wg_action': 'install', 'username': $('#username').val(), 'password': $('#password').val() },
				function(json){
					if(!json.success) {
						if(!(typeof json.fullmsg != 'undefined' && json.fullmsg == true)) {
							json.error = 'MySQL Said: ' + json.error;
						}
						showMessage('Error: Unable to install.<br/>' + json.error);
						return;
					} else {
						alert('Website Gallery has been successfully installed! You\'ll now be redirected to the Control Panel interface.');
						window.location = "index.php";
					}

				}, 'json');
			});

			var messageString = '{%message}';
			if(messageString.length > 5) {
				showMessage(messageString);
			} else {
				$('#message')
				.css('position', 'absolute')
				.css('top', '50px')
				.css('left', '5px')
				.slideDown();

			}
		});

		function showMessage (message) {
			if(message.length == 0) {
				message = "Oops! That username and password combination doesn't exist!";
			}

			$('#message').html(message);
			$('#message')
				.css('position', 'absolute')
				.css('top', '50px')
				.css('left', '5px')
				.removeClass('normalmsg')
				.slideDown();

			$('dl').css('padding-top', '0');

			resetButton('#install_button');
		}



		$(window).resize(positionLoginForm);

	</script>
</head>
<body>	<div style="text-align: center;width: 100%;">
<div id="notification-area">

		<div id="notification-error-outer">
			<div id="notification-error-inner" style="display: none" class="red_big">
				<span class="title"></span>
				<span class="message"></span>
			</div>
		</div>
	</div>
	</div>



	<div id="global_container_login" class="install_form">
		<div id="login_form" >

			<div id="message" style="display: none;" class="normalmsg"><b>Hello!</b><br/>To install your Website Gallery, enter your desired username and password below and the application will be installed!</div>
			<dl style="padding-top: 5px">
				<dt><label for="username">Username</label></dt>
				<dd><input type="text" name="username" id="username" value="" ></dd>
				<dt><label for="password">Password</label></dt>
				<dd><input type="password" name="password" id="password"></dd>

				<dd class="submit_row"><div class="button button-install" id="install_button"><div class="button-icon-bg" ><div class="button-icon"></div><div class="button-icon-loading" style="display: none;" ></div></div><div class="label">Install</div><div class="right-side-button"></div></div></dd>
				<input type="submit" style="display: none"> <img src="http://www.jordie.org/codecanyon/img/blank.gif" />
			</dl>
		</div>
	</div>
</body>
</html>