
<li class="image_item " id="image_row_{%id}">
	<div class="image_wrapper">
		<div style="background-image: url('{%thumbnail_location}');" class="album_image" id="image_{%id}">

			<div class="image_name_box" id="image_name_{%id}">{%name}</div>

			<div class="image_box image_delete_box" id="image_delete_{%id}"></div>
			<div class="image_box image_edit_box" id="image_edit_{%id}"></div>
			<div class="image_box image_cover_box" id="image_cover_{%id}"></div>
			<div class="image_box image_zoom_box" id="image_zoom_{%id}"></div>
			<div class="image_box image_rotateleft_box" id="image_rotateleft_{%id}"></div>
			<div class="image_box image_rotateright_box" id="image_rotateright_{%id}"></div>

		</div>
	</div>
</li>

